### ISSUE TITLE
VSCode trying to find find rubocop in the SYSTEM ruby

### ISSUE THREAD

**Issue by kg-currenxie** [rubocop/vscode-rubocop#21]
Hi. Having an issue to get the plugin to start.

```
[client] Command `bundle list --name-only` failed with exit code 1 (exec options: {"cwd":"/Users/frexuz/www/some-path"})
[client] stderr:
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.4.22) required by your /Users/frexuz/www//Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.4.22`
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /usr/bin/bundle:23:in `<main>'
[client] Failed to invoke Bundler in the current workspace. After resolving the issue, run the command `RuboCop: Start Language Server`
```

I use rbenv and zsh
![image](https://github.com/rubocop/vscode-rubocop/assets/48229166/729fd2e5-86f6-41b9-b67e-a7b370cfae7b)
![image](https://github.com/rubocop/vscode-rubocop/assets/48229166/21a72288-d9e6-4feb-8693-ddc7ca2812ba)
and the ruby lsp is starting fine:
![image](https://github.com/rubocop/vscode-rubocop/assets/48229166/6dcb947b-bf3a-4f0b-8ac9-c097753c1577)

I have also tried setting it directly
![image](https://github.com/rubocop/vscode-rubocop/assets/48229166/33b728b4-e46e-4307-9b31-172f72071aee)

Not sure which settings im missing 🤔

**Comment by Amnesthesia** [comment]
Same issue here, can't get this extension to use rvm Ruby

**Comment by savar** [comment]
Same issue here.. my workaround is: set the path to the rbenv installed rubocop binary and then say that you run rubocop globally and not with bundler:

![image](https://github.com/rubocop/vscode-rubocop/assets/246341/7a90de26-47d8-4a3e-ab75-8fd6f8f5b68c)

**Comment by davletovalmir** [comment]
We're using `chruby` and `ruby-install`, no luck launching it, same issue: it's trying to use Ruby of version 2.6, though we're on version 3.0.7. @savar's solution didn't help, though I tried it before discovering this thread 😞

**Comment by jherdman** [comment]
I ran into this with a colleague today as well. We found that — for whatever reason — the wrong shell was being used to launch Rubocop.

**Comment by dkniffin** [comment]
I use asdf to manage ruby, and I'm also having this issue. When I try the workaround mentioned by @savar, I start getting:

```
[client] Command `/Users/dkniffin/.asdf/shims/rubocop -v` failed with exit code 127 (exec options: {"cwd":"/Users/dkniffin/Projects/Quimbee"})
[client] stderr:
/Users/dkniffin/.asdf/shims/rubocop: line 5: exec: asdf: not found
[client] Failed to verify the version of rubocop installed, proceeding anyway...
[client] Starting language server: /Users/dkniffin/.asdf/shims/rubocop --lsp
/Users/dkniffin/.asdf/shims/rubocop: line 5: exec: asdf: not found
[Info  - 12:21:37 PM] Connection to server got closed. Server will restart.
[client] Language server initialization failed: Error: Pending response rejected since connection got disposed
[Error - 12:21:37 PM] RuboCop client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by dkniffin** [comment]
I did some digging and it looks like the line that errors for OP (and me before the workaround above), is [this one](https://github.com/rubocop/vscode-rubocop/blob/10dc3a87c28d3b46c5c4cf169829a90dac89ce41/src/extension.ts#L136). That one eventually makes it to [this one](https://github.com/rubocop/vscode-rubocop/blob/10dc3a87c28d3b46c5c4cf169829a90dac89ce41/src/extension.ts#L60), which uses node's `child_process` `exec`.

I'm not 100% sure how `exec` gets it's ENV vars set, but it seems `PATH` or something like that is being set incorrectly.

So, I figured I'd go look what other vscode linter extensions do, and if any users over there have similar issues, and I found [this similar thread on the vscode-eslint extension](https://github.com/microsoft/vscode-eslint/issues/1600). In there, it seems they also didn't quite find a solution, but OP's problem was resolved. But someone did make this comment:

> The reason for this is very likely the starting point of VS Code. When you start it from a console window that has the paths setup correctly does it fail as well?

So, I figured I'd try that. I re-started VSCode via the command line, and voila! This extension started working for me. 🎉 

I still think this is worth investigating though. It shouldn't matter how we start VSCode.

**Comment by technofreak** [comment]
It is able to load Rubocop successfully if you open it via the console (`code .`) but if we open VS Code directly from the dock or launchpad in Mac, it is not able to load Rubocop.

**Comment by ShaneCurcuru** [comment]
Can confirm: my brand new Mac Sequoia 15.7 carefully setup following all the instructions (brew, chruby/ruby-install, ruby 3.4.7, vscode 1.105.1, rubocop 1.81.6, Bundler version 2.6.9) continues to use the system ruby:

`/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.6.9) required by your /Users/curcuru/src/g/Gemfile.lock. (Gem::GemNotFound`Exception)

Would love to have the skills and time to fix this likely VSCode bug when running it from the dock.  Thanks to @dkniffin for the research!
